/// Flutter icons PoliradioAppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PoliradioAppIcons
///      fonts:
///       - asset: fonts/PoliradioAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PoliradioAppIcons {
  PoliradioAppIcons._();

  static const _kFontFam = 'PoliradioAppIcons';
  static const String? _kFontPkg = null;

  static const IconData maximize = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minimize = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaker = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
